In [1]:
import numpy as np

## Array Creation

In [2]:
# Question 1
arr_zeros = np.zeros(10)
print("Task 1:", arr_zeros)


Task 1: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Question 2
arr_float = np.arange(10, 50, dtype=float)
print("\nTask 2:", arr_float)



Task 2: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [4]:
# Question 3
matrix_ones_int = np.ones((2, 2), dtype=int)
print("\nTask 3:", matrix_ones_int)



Task 3: [[1 1]
 [1 1]]


In [5]:
# Question 4
matrix_ones_float = np.ones((3, 2), dtype=float)
print("\nTask 4:", matrix_ones_float)



Task 4: [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
# Question 5
X = np.array([[1, 2, 3], [4, 5, 6]])
ones_like_X = np.ones_like(X)
print("\nTask 5:", ones_like_X)



Task 5: [[1 1 1]
 [1 1 1]]


In [7]:
# Question 6
X = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_X = np.zeros_like(X)
print("\nTask 6:", zeros_like_X)



Task 6: [[0 0 0]
 [0 0 0]]


In [8]:
# Question 7
matrix_fives = np.full((4, 4), 5, dtype=int)
print("\nTask 7:", matrix_fives)



Task 7: [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [9]:
# Question 8
X = np.array([[1, 2, 3], [4, 5, 6]])
sevens_like_X = np.full_like(X, 7)
print("\nTask 8:", sevens_like_X)



Task 8: [[7 7 7]
 [7 7 7]]


In [10]:
# Question 9
identity_matrix = np.eye(3)
print("\nTask 9:", identity_matrix)



Task 9: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Question 10
random_integers = np.random.randint(1, 11, 3)
print("\nTask 10:", random_integers)



Task 10: [8 4 4]


In [12]:
# Question 11
random_floats = np.random.rand(3, 3, 3)
print("\nTask 11:", random_floats)



Task 11: [[[0.8991536  0.50905263 0.20059486]
  [0.53244458 0.38670698 0.67000123]
  [0.70250863 0.89907192 0.0350216 ]]

 [[0.86289647 0.96120923 0.60601655]
  [0.99821215 0.80781624 0.52970514]
  [0.24810127 0.70253906 0.31373547]]

 [[0.73215569 0.13366837 0.65212751]
  [0.31922563 0.48390611 0.44220835]
  [0.21022604 0.76129532 0.52199606]]]


In [13]:
# Question 12
arr_1_to_10 = np.arange(1, 11)
print("\nTask 12:", arr_1_to_10)



Task 12: [ 1  2  3  4  5  6  7  8  9 10]


In [14]:
# Question 13
arr_odd_numbers = np.arange(1, 11, 2)
print("\nTask 13:", arr_odd_numbers)



Task 13: [1 3 5 7 9]


In [15]:
# Question 14
arr_descending = np.arange(10, 0, -1)
print("\nTask 14:", arr_descending)



Task 14: [10  9  8  7  6  5  4  3  2  1]


In [16]:
# Question 15
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\nTask 15:", matrix_0_to_8)



Task 15: [[0 1 2]
 [3 4 5]
 [6 7 8]]


## Array Indexing

In [17]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
first_element = X[0]
print("Task 1:", first_element)


Task 1: A


In [18]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
last_element = X[-1]
print("\nTask 2:", last_element)



Task 2: E


In [19]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
first_three_elements = X[:3]
print("\nTask 3:", first_three_elements)



Task 3: ['A' 'B' 'C']


In [20]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
middle_elements = X[1:-1]
print("\nTask 4:", middle_elements)



Task 4: ['B' 'C' 'D']


In [21]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
reverse_elements = X[::-1]
print("\nTask 5:", reverse_elements)



Task 5: ['E' 'D' 'C' 'B' 'A']


In [22]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
odd_position_elements = X[::2]
print("\nTask 6:", odd_position_elements)



Task 6: ['A' 'C' 'E']


In [23]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
first_row_elements = X[0, :]
print("\nTask 7:", first_row_elements)



Task 7: [1 2 3 4]


In [24]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
last_row_elements = X[-1, :]
print("\nTask 8:", last_row_elements)



Task 8: [13 14 15 16]


In [25]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
first_element_first_row = X[0, 0]
print("\nTask 9:", first_element_first_row)



Task 9: 1


In [26]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
last_element_last_row = X[-1, -1]
print("\nTask 10:", last_element_last_row)



Task 10: 16


In [27]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
first_two_elements_first_two_rows = X[:2, :2]
print("\nTask 11:", first_two_elements_first_two_rows)



Task 11: [[1 2]
 [5 6]]


In [28]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
last_two_elements_last_two_rows = X[-2:, -2:]
print("\nTask 12:", last_two_elements_last_two_rows)



Task 12: [[11 12]
 [15 16]]


## Array Manipulation

In [29]:
# Question 1
X = np.array([-5, -3, 0, 10, 40], dtype=float)
print("Task 1:", X)


Task 1: [-5. -3.  0. 10. 40.]


In [30]:
# Question 2
X = np.array([-5, -3, 0, 10, 40])
reversed_X = X[::-1]
print("\nTask 2:", reversed_X)



Task 2: [40 10  0 -3 -5]


In [31]:
# Question 3
X = np.zeros(10)
X[4] = 1
print("\nTask 3:", X)



Task 3: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [32]:
# Question 4
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
X[-1, :] = 1
print("\nTask 4:", X)



Task 4: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


In [33]:
# Question 5
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
X = X + 5
print("\nTask 5:", X)



Task 5: [[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


#                                             Happy Learning!